#!/usr/bin/env php
<?php
require_once __DIR__ . "/../vendor/autoload.php";

define('SLACK_NOTIFICATION_HOOK', getenv('SLACK_NOTIFICATION_HOOK') ?: "");

use Mtdowling\Supervisor\EventListener;
use Mtdowling\Supervisor\EventNotification;

$listener = new EventListener();
$listener->listen(function (EventListener $listener, EventNotification $event) use ($f) {
    $state = $event->getEventName();
    if (strpos($state, 'PROCESS_STATE_') !== false) {
        $name = $event->getData('groupname') ? $event->getData('groupname') : $event->getData('processname');

        if ($state == "PROCESS_STATE_EXITED" OR $state == "PROCESS_STATE_FATAL") {
            $data = "payload=" . json_encode(["text" => "Problema na {$name}: " . date('d/m/Y H:i:s') . " State: " . $state]);

            $ch = curl_init(SLACK_NOTIFICATION_HOOK);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_exec($ch);
            curl_close($ch);
        }
    }

    return true;
});